[workspace]
[package]
name = "postgres-operator-crds"
version = "0.1.0"
edition = "2021"

[dependencies]
k8s-openapi = { version = "0.15.0", features = ["v1_20"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.82"
